### ISSUE TITLE
non-regex lists handle case sensitivity in a confusing way

### ISSUE THREAD

**Issue by luto** [haraka/haraka-plugin-access#9]
Having one of the following constellations causes the plugin to not allow addresses, which are whitelisted:

a) list says `FOO@example.com`, client says `FOO@example.com`
b) list says `foo@example.com`, client says `FOO@example.com`

while these will be allowed:

c) list says `FOO@example.com`, client says `foo@example.com`
d) list says `foo@example.com`, client says `foo@example.com`

This is because currently [`load_file()`](https://github.com/haraka/haraka-plugin-access/blob/2d183ae385384abef2c68eae5a23d7d6fd15214b/index.js#L494) converts all lists to lowerCase, but the checks do not convert the address given by the client (except for [`rdns_access`](https://github.com/haraka/haraka-plugin-access/blob/2d183ae385384abef2c68eae5a23d7d6fd15214b/index.js#L237)). Case a) vs. c) is particularly confusing.

I'd like to change this so that case is ignored in for all methods and all checks, by removing the extra code in `rdns_access` and adding a simple `address.toLowerCase()` to `in_list()`, as well as tests, ofc.
Since the RFC allows for local part of a mail address to be case sensitive, this may be a breaking change in some setups. However, I suspect that most of those setups would already be broken by behavior a) (`FOO != FOO`). If you are concerned about this, the new behavior may be hidden behind a config flag.

Please let me know what you think. I am happy to code up a PR for this once we reach a consensus about the "right" way to do this. :)

**Comment by luto** [comment]
@msimerson do you have an opinion on this?

**Comment by msimerson** [comment]
Sorry for delay, I've been away from the computer for a while.

> This is because currently load_file() converts all lists to lowerCase

This is a performance optimization. By lower casing all the entries when the file is loaded (N entries), we avoid having to lower case all the entries during every connection when comparing them (N entries  * connections). 

> but the checks do not convert the address given by the client

That's an oversight / error. The checks certainly **should** be matching with a lower cased value.

> Since the RFC allows for local part of a mail address to be case sensitive

See: https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive

Since whatever Haraka is going to deliver the message to (the "next hop") is nearly certain to be case insensitive, there's no reason to worry about case here. Just lower the value coming from the network and then compare to the already lowered values in the list.

**Comment by luto** [comment]
Thanks for your answer!

> That's an oversight / error. The checks certainly should be matching with a lower cased value.

Alright! I will prepare a PR as well as some tests then :)
